### PR TITLE
convert the package from flow to typescript - WIP

### PR DESCRIPTION
**Pull request by geekflyer**
this PR is just a work-in-progress - not to be merged. I'm just opening in case you or somebody else finds it to be useful. I'm working on some jira -> clubhouse migration scripts in node.js written in TypeScript and just prefer TypeScript over flow in general.

### CODE REVIEW

**Comment by eliperkins** [comment]
Hey! Awesome that you're working on using this (and migrating from JIRA 😉).

While we use Flow for our JS projects internally, I'd love to have a TypeScript definition to go alongside this. What do you think about creating a [type declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) and shipping it inside the module?

**Comment by geekflyer** [comment]
@eliperkins  I'll think about, meanwhile another question - is there an (inofficial) api to create users? For the story migration to work completely I need all users to be signed up to get their user uuid for story assignment.

**Comment by eliperkins** [comment]
@geekflyer There is no public API to create users, unfortunately. It sounds like a mapping between JIRA user IDs and Clubhouse user IDs is the best way forward with your script. This means that users will need to accept their invites.

If you'd like a hand on it and it's open source, I'd be happy to lend a hand!

**Comment by geekflyer** [comment]
@eliperkins I was able to hack around this limitation by using cookie based authentication to call the `invites` endpoint then using the invite id's auto automatically signup a list of given users by calling `invite/{invite-id}/create-user` - reverse engineering FTW ;-)

Anyways, I have one more problem: The stories which I create via the API and are already in completed state upon creation, don't show up in "Reports" in the week they were completed (actually they don't show up in the reports at all). I'm explicitly setting the created_at and updated_at properties, so there should be enough information for the reports to determine when the ticket completed. Any idea on how to solvve this? Perhaps this gh issue is not the right channel for those kind of questions - do you have a slack channel or can we have a call or sth?  The clubhouse org is `solvvydev` btw.

**Comment by eliperkins** [comment]
@geekflyer Stories that are created in a completed state intentionally don't show up in reports today, as no work has been done on them. 😉 They need to include a workflow state change to appear in reports.

I would suggest using our feedback on the website to open a ticket with us! We can help you out on there pretty quickly.

**Pull request closed without merging**
